const teamLogos = {
    ATL: "https://a.espncdn.com/i/teamlogos/nba/500/atl.png",
    BOS: "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
    BKN: "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png",
    CHA: "https://a.espncdn.com/i/teamlogos/nba/500/cha.png",
    CHI: "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
    CLE: "https://a.espncdn.com/i/teamlogos/nba/500/cle.png",
    DAL: "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
    DEN: "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
    DET: "https://a.espncdn.com/i/teamlogos/nba/500/det.png",
    GSW: "https://a.espncdn.com/i/teamlogos/nba/500/gs.png",
    HOU: "https://a.espncdn.com/i/teamlogos/nba/500/hou.png",
    IND: "https://a.espncdn.com/i/teamlogos/nba/500/ind.png",
    LAC: "https://a.espncdn.com/i/teamlogos/nba/500/lac.png",
    LAL: "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
    MEM: "https://a.espncdn.com/i/teamlogos/nba/500/mem.png",
    MIA: "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
    MIL: "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
    MIN: "https://a.espncdn.com/i/teamlogos/nba/500/min.png",
    NOP: "https://a.espncdn.com/i/teamlogos/nba/500/no.png",
    NYK: "https://a.espncdn.com/i/teamlogos/nba/500/ny.png",
    OKC: "https://a.espncdn.com/i/teamlogos/nba/500/okc.png",
    ORL: "https://a.espncdn.com/i/teamlogos/nba/500/orl.png",
    PHI: "https://a.espncdn.com/i/teamlogos/nba/500/phi.png",
    PHX: "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
    POR: "https://a.espncdn.com/i/teamlogos/nba/500/por.png",
    SAC: "https://a.espncdn.com/i/teamlogos/nba/500/sac.png",
    SAS: "https://a.espncdn.com/i/teamlogos/nba/500/sa.png",
    TOR: "https://a.espncdn.com/i/teamlogos/nba/500/tor.png",
    UTA: "https://a.espncdn.com/i/teamlogos/nba/500/utah.png",
    WAS: "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png",
  };
  
  export default teamLogos;